### ISSUE TITLE
Searching for specific Setting

### ISSUE THREAD

**Issue by Andsoeg** [CM-Huawei-P8-Development/device_gra_l09#16]
Whenever i search for an specific setting, no results show up.

**Comment by murdge** [comment]
For me it works since one week. Also no screen freezes.
Have you done wipe system, dalvik, cache and data partitions before installing CM?

**Comment by Andsoeg** [comment]
Yeah :)

**Comment by murdge** [comment]
So please, post your logfile that we see what happen.

**Comment by Nexolight** [comment]
Do you use that rom on a GRA-L09 with updated 6.0 ROM in advance?
Well again. Need eighter logs or clear steps to reproduce.

For me this works quite fine.

**Comment by Andsoeg** [comment]
I don't have much experience in the developing and debugging part. I just share my experience. And yes, everything in the flashing part is correct.
