### ISSUE TITLE
Many apps crashing on startup

### ISSUE THREAD

**Issue by Vaei** [CM-Huawei-P8-Development/device_gra_l09#19]
"Unfortunately, ___ has stopped." >Report/OK

This happens when _starting_ a lot of apps, this isn't the _random_ crashes as defined in the other issue.

Poweramp does this on start, however starting a second time it works until I close it then go to start it again. Camera often does this too, but it's hit or miss of it works first time. Many apps have similar issues with starting.

BigLens never works.

**Comment by Nexolight** [comment]
This belongs to the random app crashes including the logs and is probably obsolete with the next build.
The other issue was made to cut the problems down to the one or multiple causes.

-closed due to missing logs and duplice #9
