### ISSUE TITLE
USB tethering

### ISSUE THREAD

**Issue by SpeedoWBT** [CM-Huawei-P8-Development/device_gra_l09#22]
Hi Nexo , i've forget to mention that the USB tethering works with P9 framework , so i suppose the solution is here 👍
https://github.com/Meticulus/android_device_huawei_hi6250/commit/4daa61dee769c1b721ec6a1361db2cf6b4a44146

**Comment by Nexolight** [comment]
I will include it in the next build

**Comment by Nexolight** [comment]
done - fixed
