### ISSUE TITLE
No wifi tethering [again]

### ISSUE THREAD

**Issue by Beheavyon** [CM-Huawei-P8-Development/device_gra_l09#34]
Hello.
This functions is should be working (as you said).
But i can manipulate with icon what disapper after ending the editing. Also aps from market (i tested many of it) doesn't work. Other devices can not conect to phone.

**Comment by Nexolight** [comment]
![screenshot_20180418-194730](https://user-images.githubusercontent.com/7711052/38949162-eabe377e-4341-11e8-88ab-4b7937fc7625.png)
![screenshot_20180418-194746](https://user-images.githubusercontent.com/7711052/38949179-f281b56c-4341-11e8-950e-3ff26d302bf9.png)
![screenshot_20180418-194811](https://user-images.githubusercontent.com/7711052/38949192-f93dee2a-4341-11e8-89b9-2dd84fed1372.png)

**Comment by Nexolight** [comment]
Settings -> More... -> Tethering & mobile hotspot -> Mobile WLAN-Hotspot.

It is there and works for me. Connecting and using the hotspot does work pretty well for me as well.
