### ISSUE TITLE
Feature: SDCard

### ISSUE THREAD

**Issue by Nexolight** [CM-Huawei-P8-Development/device_gra_l09#7]
SDCard isn't reconized in the system yet. For recovery it is fine.

**Comment by PaulFasola** [comment]
Fixed in my Huawei Next's build, I don't remember well but I'll find and PR you the fix ;)

**Comment by SpeedoWBT** [comment]
persist.fw.force_adoptable=true
must be  in system.prop (build.prop) to complete the fix as well

**Comment by Nexolight** [comment]
It's applied here 42f81fc7245fbbf4a42378657f7ded23819fdc53
I can't test it (don't have a sdcard right now). I will reopen if someone reports issues.

**Comment by Mosterxxx** [comment]
Hey Guys,
I have already downloaded last build but i have problem with the sd card, 
At the time of trying to format it Throws this error "Command '19 volume partition disk:179_160 private' failed with '400 19 Command failed', any solution?.

**Comment by ayesse** [comment]
Same issue as @Mosterxxx

**Comment by Nexolight** [comment]
Does an external format with fat32 fs help?

Well the fix was untested (As I said I don't have an sdcard to test atm)

**Comment by Mosterxxx** [comment]
I try to change the FS of exFAT(FAT32) to NTFS and EXT2 but has failed with any of these.

**Comment by murdge** [comment]
For me it works after formatting with SD Card Formatter (exFAT only)
[https://www.sdcard.org/downloads/formatter_4/](url)

**Comment by Mosterxxx** [comment]
Thx @murdge , Now works for me, after formatting with you app, but i can't use as primary storage... still needs formatting to use as primary storage.

**Comment by Nexolight** [comment]
What about mounting it directly via command line?

I'm not familiar with that stuff. Earlier on other roms I had sdcard and sdcard1 folder.

I need to check the ramdisk can't remember what the fix was but trying to mount it as vfat into /sdcard (I assume that's what you mean with as internal storage) would of curse fail when the sdcard is formated with exFAT.

I'm a bit confused about vold and how it does work. But if it would be just a plain fstab entry I could set the fs to automatic.

**Comment by Nexolight** [comment]
The other question is why does it work with exFAT and nothing else ?!?

**Comment by murdge** [comment]
There where always problems with P8 and SD Card. You can find more here if you can read german:
[http://www.android-hilfe.de/thema/voller-zugriff-auf-externe-sd-mit-xinternalsd-xposed-modul.783647/](url)
There is also rufus.wilson at xda [https://forum.xda-developers.com/android/software/fix-extsd-fix-v1-0b-2016-01-18-t3296266](url) who tried to make a patch for MM. Maybe it helps to contakt him.

**Comment by Nexolight** [comment]
The SDCard itself does work - formating it is what is broken.
